import MainSidebar from '@/components/main-sidebar/main-sidebar';
import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className=" w-full h-full xl:flex ">
          <div className="  h-full  hidden xl:block">
            <MainSidebar />
          </div>

          <div className=" w-full   px-5 xl:px-10">{children}</div>
        </main>
      </body>
    </html>
  );
}
