import {
  Alergista,
  Anestesiologia,
  Angiologia,
  Cardiologia_Pediátrica,
  Cirurgia_Plástica,
  Clínico_Geral,
  Coloproctologia,
  EndocrinologistaPed,
  Fisioterapia,
  Gastrologia,
  Geriatra,
  Ginecologia,
  Hematologia,
  Homeopatia,
  Massoterapia,
  Medicina_do_trabalho,
  Neurologia,
  Nutrição,
  Nutrição_Esportiva,
  Odontologia,
  Oftalmologia,
  Ortopedia,
  Otorrinolaringologista,
  Pediatra,
  Pilates,
  Pneumologia,
  Podologia,
  Proctologia,
  Psicologia,
  Psicopedagogia,
  Psiquiatria,
  Psiquiatria_Infantil,
  Reumatologia,
  TratamentoObesidade,
  Urologia,
} from "@/assets/plans";

export const plansData = [
  {
    name: "Alergista",
    icon: Alergista,
    id: "1",
  },
  {
    name: "Anestesiologia",
    icon: Anestesiologia,
    id: "2",
  },
  {
    name: "Angiologia",
    icon: Angiologia,
    id: "3",
  },
  {
    name: "Cardiologia Pediátrica",
    icon: Cardiologia_Pediátrica,
    id: "4",
  },
  {
    name: "Cirurgia Plástica ",
    icon: Cirurgia_Plástica,
    id: "5",
  },
  {
    name: "Clínico Geral ",
    icon: Clínico_Geral,
    id: "6",
  },
  {
    name: "Pediatra ",
    icon: Pediatra,
    id: "7",
  },
  {
    name: "Oftalmologia",
    icon: Oftalmologia,
    id: "8",
  },
  {
    name: "Medicina do trabalho ",
    icon: Medicina_do_trabalho,
    id: "9",
  },
  {
    name: "Hematologia",
    icon: Hematologia,
    id: "10",
  },
  {
    name: "Odontologia ",
    icon: Odontologia,
    id: "11",
  },
  {
    name: "Ortopedia",
    icon: Ortopedia,
    id: "12",
  },
  {
    name: "Pneumologia",
    icon: Pneumologia,
    id: "13",
  },
  {
    name: "Reumatologia",
    icon: Reumatologia,
    id: "14",
  },
  {
    name: "Psiquiatria Infantil",
    icon: Psiquiatria_Infantil,
    id: "15",
  },
  {
    name: "Otorrinolaringologista",
    icon: Otorrinolaringologista,
    id: "16",
  },
  {
    name: "Massoterapia",
    icon: Massoterapia,
    id: "17",
  },
  {
    name: "Podologia",
    icon: Podologia,
    id: "18",
  },
  {
    name: "Tratamento Obesidade",
    icon: TratamentoObesidade,
    id: "19",
  },
  {
    name: "Pilates",
    icon: Pilates,
    id: "20",
  },
  {
    name: "Urologia",
    icon: Urologia,
    id: "21",
  },
  {
    name: "Nutrição ",
    icon: Nutrição,
    id: "22",
  },
  {
    name: "Nutrição Esportiva",
    icon: Nutrição_Esportiva,
    id: "23",
  },
  {
    name: "Nutrição Funcional ",
    icon: Psicologia,
    id: "24",
  },
  {
    name: "Nutrologia    ",
    icon: Neurologia,
    id: "25",
  },
  {
    name: "Medicina Integrativa     ",
    icon: Gastrologia,
    id: "26",
  },
  {
    name: "Fisioterapia ",
    icon: Fisioterapia,
    id: "27",
  },
  {
    name: "Geriatra ",
    icon: Geriatra,
    id: "28",
  },
  {
    name: "Endocrinologista Ped  ",
    icon: EndocrinologistaPed,
    id: "29",
  },
  {
    name: "Gastrologia",
    icon: Gastrologia,
    id: "30",
  },
  {
    name: "Ginecologia ",
    icon: Ginecologia,
    id: "31",
  },
  {
    name: "Homeopatia",
    icon: Homeopatia,
    id: "32",
  },
  {
    name: "Psiquiatria   ",
    icon: Psiquiatria,
    id: "33",
  },
  {
    name: "Quiropraxia  ",
    icon: Proctologia,
    id: "34",
  },
  {
    name: "Proctologia     ",
    icon: Proctologia,
    id: "35",
  },
  {
    name: "Coloproctologia     ",
    icon: Coloproctologia,
    id: "36",
  },
  {
    name: "Psicopedagogia     ",
    icon: Psicopedagogia,
    id: "37",
  },
];
